ZSH_THEME="norm"
plugins=(
  git zsh-autosuggestions zsh-syntax-highlighting lol
)
alias gp="git pull"
alias gps="git push"
alias gcm="git commit -m"
alias ga="git add -A ."
alias dc="docker-compose"
alias gl="git log -n"
alias gf="git fetch"
alias gc="git checkout"
alias gs="git status"
alias gst="git stash"
alias gpm="git pull origin master"
alias dcd="docker-compose -f docker-compose-dev.yml"
alias dcl="docker-compose logs"
alias ll="ls -la"
alias yi="yarn install"
alias yl="yarn lint"
alias ya="yarn android"
alias ys="yarn start"
alias yeet="yart test -u"
alias yb="yarn build"
alias yt="yarn test"
alias sr="swift run"
